#Area of a triangle

triangle_base = float(input("Enter the base of the triangle: "))
triangle_height = float(input("Enter the height of the triangle: "))

area = 0.5 * triangle_base * triangle_height
print("The area is",area)

#Area of a rectangle

rect_len = float(input("Enter the length of the rectangle: "))
rect_width = float(input("Enter the width of the rectangle: "))

area = rect_len * rect_width
print("The area is",area)

